name       : ldns
version    : 1.8.3
release    : 6
source     :
    - https://github.com/NLnetLabs/ldns/archive/refs/tags/1.8.3.tar.gz : 33fb1a77f2de2fca9e749d17256334a3222a9e9d11b31c6d998bd920f3bd6776
license    : BSD-3-Clause
component  :
    - programming.library
    - utils : network.util
summary    : ldns library for DNS programming
description:
    - The goal of ldns is to simplify DNS programming, it supports recent RFCs like the DNSSEC documents, and allows developers to easily create software conforming to current RFCs, and experimental software for current Internet Drafts.
    - utils : Drill and ldns examples. Drill is a tool to designed to get all sorts of information out of the DNS. It is specificly designed to be used with DNSSEC. The examples are example programs of ldns usage.
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
    - devel :
        - /usr/bin/ldns-config
        - /usr/share/man/man1/ldns-config.1
setup      : |
    libtoolize -ci
    %reconfigure --disable-dane-ta-usage --with-drill --with-examples
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 packaging/libldns.pc $installdir/usr/lib64/pkgconfig/libldns.pc
