name       : ldns
version    : 1.7.1
release    : 4
source     :
    - https://github.com/NLnetLabs/ldns/archive/release-1.7.1.tar.gz : 168ddc2ab0907079d537fe470e408e766f81a36323367a719a9336ff7b71284e
license    : BSD-3-Clause
component  :
    - programming.library
    - utils : network.util
summary    : ldns library for DNS programming
description:
    - The goal of ldns is to simplify DNS programming, it supports recent RFCs like the DNSSEC documents, and allows developers to easily create software conforming to current RFCs, and experimental software for current Internet Drafts.
    - utils : Drill and ldns examples. Drill is a tool to designed to get all sorts of information out of the DNS. It is specificly designed to be used with DNSSEC. The examples are example programs of ldns usage.
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
    - devel :
        - /usr/bin/ldns-config
        - /usr/share/man/man1/ldns-config.1
        - /usr/share/man/man3
setup      : |
    libtoolize -ci
    %reconfigure --disable-dane-ta-usage --with-drill --with-examples
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 packaging/libldns.pc $installdir/usr/lib64/pkgconfig/libldns.pc
